#include "channel.hpp"
#include "metainfo.hxx"
#include "unitproto.hpp"
#include "BasicUnits/BinaryGenerator.hpp"
#include "BasicUnits/BinarySymmetricChannel.hpp"
#include "BasicUnits/MarkovBinaryChannel.hpp"
#include "BasicUnits/RepetitionCoder.hpp"
#include "BasicUnits/BCH.hpp"
#include "BasicUnits/DataLogger.hpp"
#include "LDPC/Decoder.hpp"
#include "LDPC/CodewordGenerator.hpp"
#include "BasicUnits/ErrorCounter.hpp"
#include "BasicUnits/GaussianChannel.hpp"
#include "BasicUnits/Modulator.hpp"

#include <iostream>
